# Generated by Django 3.0 on 2022-11-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discount',
            field=models.CharField(default='NEW10', max_length=100),
        ),
    ]
