# Generated by Django 3.0 on 2022-11-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_user_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='discount',
        ),
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.CharField(default='NEW10', max_length=100),
        ),
    ]
